# Generated by Django 5.0.7 on 2024-09-05 08:00

from django.db import migrations, models #type:ignore


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Read',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countrycode', models.CharField(max_length=200, null=True)),
                ('coordinate', models.CharField(max_length=200, null=True)),
                ('temp', models.IntegerField(max_length=200, null=True)),
                ('humidity', models.IntegerField(max_length=200, null=True)),
            ],
        ),
    ]
